// frontend/apps/web/components/auth/LoginCard.tsx
'use client'

import { useRouter } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useToast } from '@/components/ui/use-toast'
import { useLogin } from '@/hooks/useLogin'
import {
  useField,
  required,
  email as emailRule,
} from '@repo/shared/hooks/useFieldValidation'

export function LoginCard() {
  const router = useRouter()
  const { toast } = useToast()
  const { login, loading } = useLogin()

  const email = useField('', [required(), emailRule('Adresse email invalide')])
  const password = useField('', [required('Le mot de passe est requis')])

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const valid = [email.validate(), password.validate()].every(Boolean)
    if (!valid) return

    const result = await login({ email: email.value, password: password.value })

    if (result.ok) {
      router.push('/dashboard')
    } else {
      toast({
        title: 'Erreur de connexion',
        description: 'Email ou mot de passe incorrect',
        variant: 'destructive',
      })
    }
  }

  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="items-center gap-3">
        <CardTitle>Connexion</CardTitle>
      </CardHeader>
      <CardContent>
        <form className="space-y-4" noValidate onSubmit={handleSubmit}>
          <Input
            label="Email"
            type="email"
            name="email"
            placeholder="jean@exemple.com"
            value={email.value}
            onChange={(e) => email.setValue(e.target.value)}
            onBlur={email.touch}
            error={email.error}
            disabled={loading}
          />
          <Input
            label="Mot de passe"
            type="password"
            name="password"
            placeholder="Votre mot de passe"
            value={password.value}
            onChange={(e) => password.setValue(e.target.value)}
            onBlur={password.touch}
            error={password.error}
            disabled={loading}
          />
          <Button type="submit" className="w-full" disabled={loading}>
            {loading ? 'Connexion...' : 'Se connecter'}
          </Button>
        </form>

        <p className="mt-4 text-center text-sm text-muted-foreground">
          Pas de compte ?{' '}
          <a href="/signup" className="text-primary hover:underline">
            Créer un compte
          </a>
        </p>
      </CardContent>
    </Card>
  )
}

// frontend/components/auth/LoginCard.vue
<script setup lang="ts">
import { useField } from '~/composables/useField'
import { email as emailRule, required } from '~/utils/validators'

defineProps<{
  loading: boolean
}>()

const emit = defineEmits<{
  submit: [{ email: string; password: string }]
}>()

const {
  value: email,
  errorMessage: emailError,
  handleBlur: handleBlurEmail,
  validate: validateEmail,
} = useField('', [required(), emailRule('Adresse email invalide')])

const {
  value: password,
  errorMessage: passwordError,
  handleBlur: handleBlurPassword,
  validate: validatePassword,
} = useField('', [required()])

function handleSubmit() {
  const valid = [validateEmail, validatePassword].every((fn) => fn())
  if (valid) {
    emit('submit', { email: email.value, password: password.value })
  }
}
</script>

<template>
  <Card variant="shadow" class="w-full max-w-sm">
    <div class="flex flex-col items-center gap-3">
      <AppLogo size="md" />
      <Heading :level="1" size="lg">Connexion</Heading>
    </div>

    <form class="space-y-4" novalidate @submit.prevent="handleSubmit">
      <Input
        v-model="email"
        type="email"
        name="email"
        label="Email"
        placeholder="jean@exemple.com"
        :error="emailError"
        :disabled="loading"
        @blur="handleBlurEmail()"
      />

      <Input
        v-model="password"
        type="password"
        name="password"
        label="Mot de passe"
        placeholder="Votre mot de passe"
        :error="passwordError"
        :disabled="loading"
        @blur="handleBlurPassword()"
      />

      <Button
        type="submit"
        variant="primary"
        full-width
        :loading="loading"
      >
        Se connecter
      </Button>
    </form>

    <div class="flex flex-col items-center gap-1 mt-2">
      <Text as="p" class="text-center">
        <AppLink variant="brand" to="/auth/forgot-password">Mot de passe oublié ?</AppLink>
      </Text>
      <Text as="p" class="text-center">
        Pas encore de compte ?
        <AppLink variant="brand" to="/auth/signup">S'inscrire</AppLink>
      </Text>
    </div>
  </Card>
</template>
