// frontend/components/ui/Input.vue
<script setup lang="ts">
defineProps<{
  modelValue?: string
  type?: 'text' | 'email' | 'password'
  label?: string
  placeholder?: string
  name?: string
  error?: string
  disabled?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()
</script>

<template>
  <div class="flex flex-col gap-1">
    <label
      v-if="label"
      :for="name"
      class="text-sm font-medium text-gray-700 dark:text-gray-300"
    >
      {{ label }}
    </label>

    <div
      :class="[
        'flex h-12 w-full items-center gap-2 rounded-xl border bg-white/0 px-3',
        'text-sm text-gray-800 dark:text-white',
        'transition-colors duration-150',
        error
          ? 'border-red-400 focus-within:border-red-500 dark:border-red-500'
          : 'border-gray-200 focus-within:border-brand-500 dark:border-white/10 dark:focus-within:border-brand-400',
        disabled && 'cursor-not-allowed opacity-40',
      ]"
    >
      <slot name="prefix" />
      <input
        :id="name"
        :type="type ?? 'text'"
        :value="modelValue"
        :placeholder="placeholder"
        :name="name"
        :disabled="disabled"
        class="min-w-0 flex-1 bg-transparent outline-none placeholder:text-gray-400 dark:placeholder:text-gray-500"
        @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
      />
      <slot name="suffix" />
    </div>

    <p v-if="error" class="text-xs text-red-500">{{ error }}</p>
  </div>
</template>

// frontend/apps/web/components/ui/input.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'
import { Label } from './label'

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string
  error?: string
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, label, error, id, ...props }, ref) => {
    const inputId = id ?? label?.toLowerCase().replace(/\s+/g, '-')
    return (
      <div className="space-y-1">
        {label && (
          <Label htmlFor={inputId}>{label}</Label>
        )}
        <input
          id={inputId}
          type={type}
          className={cn(
            'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
            error && 'border-destructive focus-visible:ring-destructive',
            className
          )}
          ref={ref}
          aria-invalid={!!error}
          aria-describedby={error ? `${inputId}-error` : undefined}
          {...props}
        />
        {error && (
          <p id={`${inputId}-error`} className="text-sm text-destructive">
            {error}
          </p>
        )}
      </div>
    )
  }
)
Input.displayName = 'Input'

export { Input }
