// frontend/components/auth/SignupCard.vue
<script setup lang="ts">
defineProps<{
  loading: boolean
  error: string | null
}>()

const emit = defineEmits<{
  submit: [{ name: string; email: string; password: string }]
}>()

const name = ref('')
const email = ref('')
const password = ref('')

const errors = reactive({ name: '', email: '', password: '' })

function validate(): boolean {
  errors.name = ''
  errors.email = ''
  errors.password = ''

  let valid = true

  if (!name.value.trim()) {
    errors.name = 'Le nom est requis'
    valid = false
  }

  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value)) {
    errors.email = 'Adresse email invalide'
    valid = false
  }

  if (password.value.length < 8) {
    errors.password = 'Le mot de passe doit contenir au moins 8 caractères'
    valid = false
  }

  return valid
}

function handleSubmit() {
  if (validate()) {
    emit('submit', { name: name.value, email: email.value, password: password.value })
  }
}
</script>

<template>
  <div class="bg-white rounded-2xl p-8 w-full max-w-sm shadow-sm space-y-5">
    <div class="flex flex-col items-center gap-3">
      <AppLogo size="md" />
      <h1 class="text-lg font-semibold text-gray-900 dark:text-white">
        Créer un compte
      </h1>
    </div>

    <form class="space-y-4" @submit.prevent="handleSubmit">
      <Input
        v-model="name"
        type="text"
        name="name"
        label="Nom complet"
        placeholder="Jean Dupont"
        :error="errors.name"
        :disabled="loading"
      />

      <Input
        v-model="email"
        type="email"
        name="email"
        label="Email"
        placeholder="jean@exemple.com"
        :error="errors.email"
        :disabled="loading"
      />

      <Input
        v-model="password"
        type="password"
        name="password"
        label="Mot de passe"
        placeholder="8 caractères minimum"
        :error="errors.password"
        :disabled="loading"
      />

      <p v-if="error" class="text-sm text-red-500">{{ error }}</p>

      <Button
        type="submit"
        variant="primary"
        full-width
        :loading="loading"
      >
        Créer mon compte
      </Button>
    </form>

    <p class="text-center text-sm text-gray-500">
      Déjà un compte ?
      <NuxtLink to="/auth/login" class="font-medium text-brand-500 hover:underline">
        Se connecter
      </NuxtLink>
    </p>
  </div>
</template>

// frontend/apps/web/components/auth/SignupCard.tsx
"use client";

import { useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/use-toast";
import { useSignup } from "@repo/shared/hooks/useSignup";
import {
  useField,
  required,
  email as emailRule,
  min,
} from "@repo/shared/hooks/useFieldValidation";

export function SignupCard() {
  const router = useRouter();
  const { toast } = useToast();
  const { signup, loading } = useSignup();

  const firstName = useField("", [required("Le prénom est requis")]);
  const lastName = useField("", [required("Le nom est requis")]);
  const email = useField("", [required(), emailRule("Adresse email invalide")]);
  const password = useField("", [
    required(),
    min(8, "Le mot de passe doit contenir au moins 8 caractères"),
  ]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const valid = [
      firstName.validate(),
      lastName.validate(),
      email.validate(),
      password.validate(),
    ].every(Boolean);
    if (!valid) return;

    const result = await signup({
      firstName: firstName.value,
      lastName: lastName.value,
      email: email.value,
      password: password.value,
    });

    if (result.ok) {
      toast({
        title: "Bienvenue !",
        description: "Compte créé avec succès",
        variant: "success",
      });
      router.push("/");
    } else {
      const err = result.error;
      let description = "Une erreur est survenue, veuillez réessayer";
      if (err.status === 422) {
        const hasViolations =
          Array.isArray(err.data?.violations) && err.data.violations.length > 0;
        description = hasViolations
          ? "Données invalides. Vérifiez vos informations."
          : "Email déjà utilisé";
      } else if (err.status === 500) {
        description = "Erreur serveur. Veuillez réessayer plus tard";
      } else {
        description = err.data?.message || err.message || description;
      }
      toast({
        title: "Erreur de connexion",
        description,
        variant: "destructive",
      });
    }
  }

  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="items-center gap-3">
        <CardTitle>Créer un compte</CardTitle>
      </CardHeader>
      <CardContent>
        <form className="space-y-4" noValidate onSubmit={handleSubmit}>
          <Input
            label="Prenom"
            type="text"
            name="firstName"
            placeholder="Jean Dupont"
            value={firstName.value}
            onChange={(e) => firstName.setValue(e.target.value)}
            onBlur={firstName.touch}
            error={firstName.error}
            disabled={loading}
          />
          <Input
            label="Nom"
            type="text"
            name="lastName"
            placeholder="Jean Dupont"
            value={lastName.value}
            onChange={(e) => lastName.setValue(e.target.value)}
            onBlur={lastName.touch}
            error={lastName.error}
            disabled={loading}
          />
          <Input
            label="Email"
            type="email"
            name="email"
            placeholder="jean@exemple.com"
            value={email.value}
            onChange={(e) => email.setValue(e.target.value)}
            onBlur={email.touch}
            error={email.error}
            disabled={loading}
          />

          <Input
            label="Mot de passe"
            type="password"
            name="password"
            placeholder="8 caractères minimum"
            value={password.value}
            onChange={(e) => password.setValue(e.target.value)}
            onBlur={password.touch}
            error={password.error}
            disabled={loading}
          />

          <Button type="submit" className="w-full" disabled={loading}>
            {loading ? "Création..." : "Créer mon compte"}
          </Button>
        </form>

        <p className="mt-4 text-center text-sm text-muted-foreground">
          Déjà un compte ?{" "}
          <a href="/login" className="text-primary hover:underline">
            Se connecter
          </a>
        </p>
      </CardContent>
    </Card>
  );
}
